# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FootyOrg' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FootyOrg
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'OptimizelySDKiOS'

  target 'FootyOrgTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FootyOrgUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
